### ISSUE TITLE
[FEATURE REQUEST] Speed up the engine without lowering the power

### ISSUE THREAD

**Issue by BayuSJW** [gmcheems/gmcheems#1]
**Is your feature request related to a problem? Please describe.**
I sometimes lose in 30 second games due to running out of time and a weak engine (I set the engine depth to 5, and turn off the delay to make it faster but the engine is getting weaker)

**Describe the solution you'd like**
the machine can move faster but also stay strong, for example with 15 depth can win in the game 30 seconds of time and strength

**Describe alternatives you've considered**
I dunno, I don't really know about this

**Additional context**
no, and I think this extension is very good.

**Comment by BayuSJW** [comment]
I'm using Helio A22 2.00 GHz, it's a mobile CPU, now I understand why it happened, and by the way this extension works fine on android, thanks for the help.

> What's your CPU? Higher depth = more computation, so if you want to be able to keep the depth the same, but compute in a shorter time, you'll need a stronger CPU.
> 
> We're currently on stockfish 11, but I'm upgrading it for the next release, so hopefully we'll get some performance improvements.

I'm using Helio A22 2.00 GHz, it's a mobile CPU, now I understand why it happened, and by the way this extension works fine on android, thanks for the help.

**Comment by gmcheems** [comment]
@BayuSJW Wow i had no idea you could even run it on mobile 😮 

Can you post a screenshot of what it looks like? Really curios ..

**Comment by BayuSJW** [comment]
> @BayuSJW Wow i had no idea you could even run it on mobile 😮
> 
> Can you post a screenshot of what it looks like? Really curios ..

I use Kiwi Browser because it supports extensions, after I tried it worked fine.

![Screenshot_20220629-104659](https://user-images.githubusercontent.com/93809333/176347565-a6a722ad-72b6-4824-917f-d43cd1c6f60f.png)

![Screenshot_20220629-104708](https://user-images.githubusercontent.com/93809333/176347617-c30889d4-e4a1-4e1f-8433-76a52ef6f1e6.png)

![Screenshot_20220629-104715](https://user-images.githubusercontent.com/93809333/176347650-0e3c5f01-abd6-4e63-a9a2-07292099c2c2.png)

I don't know if the browser is chromium-based or not, but it works.

**Comment by gmcheems** [comment]
@BayuSJW wow, i'm speechless.

Just googled it, it is chromium-based. 

Thanks for the ticket, I may add support for mobile now that I know people are using it there 🙂
