### ISSUE TITLE
Bypass anti-cheat(Simulate human moves)

### ISSUE THREAD

**Issue by VortexFlickens** [gmcheems/gmcheems#10]
**Is your feature request related to a problem? Please describe.**
The problem is getting banned:(

**Describe the solution you'd like**
I need a "Simulate human moves feature" similar to that of chessbotx

**Describe alternatives you've considered**
Any alternative that helps me win and also not get banned. 

**Additional context**

![msedge_f9xHYpn2iH](https://user-images.githubusercontent.com/106667615/179269392-9c1b72c5-9507-4b1b-a224-add818467046.png)

**Comment by gmcheems** [comment]
@VortexFlickens Can you give me an idea of how this works or what it does?

**Comment by OgnistyPoland** [comment]
I guess it is random delay from 1-5s and sometimes making errors
