### ISSUE TITLE
Stockfish 15

### ISSUE THREAD

**Issue by gmcheems** [gmcheems/gmcheems#6]
0.2.1 and prior run on Stockfish 11. Need to upgrade to 15.

**Comment by gmcheems** [comment]
I'm facing technical difficulties while trying to add support for Stockfish 15. It's complicated but will update this thread on the progress.

For now, I'm sidelining it as I have no good solution in mind.

**Comment by VortexFlickens** [comment]
Hey @gmcheems is it possible that ur tampermonkey extention runs stockfish?

**Comment by VortexFlickens** [comment]
IS ur  kodama latest?

**Comment by VortexFlickens** [comment]
Issue resolved :)
https://github.com/nmrugg/stockfish.js/

**Comment by gmcheems** [comment]
I'm aware of that, that's what I'm working with, but like I said, it's not simple or easy.

**Comment by VortexFlickens** [comment]
> I'm aware of that, that's what I'm working with, but like I said, it's not simple or easy.

Sorry but I am curious and just want to know how much time it would to upgrade to stockfish 15 take by estimation. 
I am asking this cuz I want to make  a YouTube video of gmcheems defeating max engine elo 3200 which currently it doesn't.

**Comment by gmcheems** [comment]
@VortexFlickens There's no ETA

**Comment by gmcheems** [comment]
@VortexFlickens See the update https://github.com/gmcheems/gmcheems/discussions/14

I'll be looking into getting Stockfish 15 working soon.
