### ISSUE TITLE
[FEATURE REQUEST] Automation to find new opponents, and accept rematches.

### ISSUE THREAD

**Issue by PotatoGaming8K** [gmcheems/gmcheems#8]
**Is your feature request related to a problem? Please describe.**
I'm tired of pressing the button after the game ends.

**Describe the solution you'd like**
Add these two features:
- Automatically search for new opponents when the game ends.

- Automatically accepts rematch.

**Describe alternatives you've considered**
I don't know

**Additional context**
What i want is to add a checkbox or whatever for those two features, for example if i activate both features but my enemy doesn't offer a rematch, it will automatically look for a new opponent, but if my opponent offers a rematch, then automatically accept the rematch, that's the point .

**Comment by gmcheems** [comment]
Yes, it's been on my mind for a while. I'll put it on the roadmap.

**Comment by gmcheems** [comment]
See the update https://github.com/gmcheems/gmcheems/discussions/14
Auto-play next match is added in 0.5.0 but auto-accept rematch will come later.
