### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by VortexFlickens** [gmcheems/gmcheems#9]
**Describe the bug**(Not necessary to fix)
Always draw with elo 3200 engine

IDK know the steps to fix it. But its okay if it's not fixed provided u add stockfish 15.

**Expected behavior**
IT should predict draw by repeating three moves

**Debug information and screenshot**
![msedge_dyKpP7cgb8](https://user-images.githubusercontent.com/106667615/179268552-435cc6eb-feae-4416-88f4-545013ecfb8e.png)

**Comment by gmcheems** [comment]
This isn't a bug, this is the engine's limitations, which is out of my control (assuming you have the highest engine settings)
